// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn_1QYTvf7kQuzGe38AO0j5WZUsyPd_VE',
    appId: '1:855422049492:web:5c55bc93c19595eb922f41',
    messagingSenderId: '855422049492',
    projectId: 'deliver-29f3a',
    authDomain: 'deliver-29f3a.firebaseapp.com',
    storageBucket: 'deliver-29f3a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVGA6urzkqFou0FA4RxI5BHnDswqRWRzo',
    appId: '1:855422049492:android:4129a0f2cb4c6cc7922f41',
    messagingSenderId: '855422049492',
    projectId: 'deliver-29f3a',
    storageBucket: 'deliver-29f3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZiFVhxVdhJViuXDNZ3mlqg2U0CGotnBM',
    appId: '1:855422049492:ios:b0ec2e6ed3519034922f41',
    messagingSenderId: '855422049492',
    projectId: 'deliver-29f3a',
    storageBucket: 'deliver-29f3a.appspot.com',
    iosClientId: '855422049492-0377nr5gg65akmjqej0vj5jdddq72ks7.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliver',
  );
}
