default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk"
    firebase_app_distribution(
        app: "1:855422049492:android:9f51e70785e3a18d922f41",
        firebase_cli_token: "1//09wSi_9I3M4e-CgYIARAAGAkSNwF-L9Ir1pe_kyFk5-4PiUCXIuuwy7knyd2U6pZWc4aK4nOHYy5rULOcZIG0rAd6bGD-528t8zA",
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
        testers: "mehsen2222@gmail.com",
        release_notes: "First release by fastlane firebase app distribution :)"
      )
  end
end
