default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    google_maps_key = ENV["GOOGLE_MAP_KEY"]
    if google_maps_key.nil? || google_maps_key.empty?
        UI.user_error!("Google Maps API Key is missing!")
    end
    File.open("../android/local.properties","a") do |f|
    f.puts "google_maps_key=#{google_maps_key}"
    end
    sh "flutter build apk --release"
    firebase_app_distribution(
        app: "1:855422049492:android:9f51e70785e3a18d922f41",
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
        testers: "mehsen2222@gmail.com",
        release_notes: "Release by github actions :)"
      )
  end
end
